project:
  type: website

website:
  title: "Job Market Analysis 2024"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: prompt.qmd
        text: "Research Introduction and Rationale"
      - href: ai_vs_traditional.qmd
        text: "Ai vs Traditional"
      - href: data_analysis.qmd
        text: "Data Analysis"
      - href: skill_gap_analysis.qmd
        text: "Skill Gap Analysis"
      - href: ml_methods_2.qmd
        text: "ML Methods"


format:
  html:
    theme: cosmo
    toc: true

execute:
  echo: true
  eval: true
  code-fold: true