---
title: "Data Analysis"
subtitle: "Comprehensive Data Cleaning & Exploratory Analysis of Job Market Trends"
author:
  - name: Norah Jones
    affiliations:
      - id: bu
        name: Boston University
        city: Boston
        state: MA
  - name: John Hamm
    affiliations:
      - ref: bu
bibliography: references.bib
csl: csl/econometrica.csl
format: 
  html:
    echo: false
    toc: true
    number-sections: true
    df-print: paged
---

## Dropping Unnecessary Columns


The Unnecessary Columns:


- ID
- URL
- ACTIVE_URLS
- DUPLICATES
- LAST_UPDATED_TIMESTAMP
- NAICS2
- NAICS3
- NAICS4
- NAICS5
- NAICS6
- SOC_2
- SOC_3
- SOC_5


With the removal of older NAICS and SOC codes, our dataset now retains only the most current classification columns: NAICS_2022_6 for industry and SOC_2021_4 for occupation. This streamlines our analysis by focusing on up-to-date standards, reducing redundancy, and ensuring consistency in categorizing job postings.


```{python echo=false}
import pandas as pd


#df = pd.read_csv('data/lightcast_job_postings.csv', low_memory=False)


columns_to_drop = [
  "ID", "URL", "ACTIVE_URLS", "DUPLICATES", "LAST_UPDATED_TIMESTAMP",
  "NAICS2", "NAICS3", "NAICS4", "NAICS5", "NAICS6",
  "SOC_2", "SOC_3", "SOC_5"
]
df.drop(columns=columns_to_drop, inplace=True)


```





```{python echo=false}
#import missingno as msno
#import matplotlib.pyplot as plt


#msno.heatmap(df)
#plt.title("Missing Values Heatmap")



# Fill missing values for SALARY before dropping columns with many missing values
#if "SALARY" in df.columns:
# df["SALARY"] = df["SALARY"].fillna(df##["SALARY"].median())


#df = df.drop_duplicates(subset=["TITLE", "COMPANY", "LOCATION", "POSTED"], keep="first")
```







```{python echo=false}
df = df.drop_duplicates(subset=["TITLE", "COMPANY", "LOCATION", "POSTED"], keep="first")






```


## Job Postings by Industry

```{python echo=false}

import plotly.express as px

industry_counts = df["NAICS_2022_6_NAME"].value_counts().reset_index()
industry_counts.columns = ["Industry", "Number of Job Postings"]

top_industries = industry_counts.head(20)

fig = px.bar(top_industries,
            x="Industry",
            y="Number of Job Postings",
            title="Top 20 Job Postings by Industry",
            width=900,
            height=600)

fig.update_xaxes(tickangle=45, tickmode='array')

fig.write_html("figures/top_20_job_postings_by_industry.html")


```


```{=html}
<iframe src="figures/top_20_job_postings_by_industry.html" width="800" height="600" frameborder="0"></iframe>

```

The amount of jobs an industry publishes is indicative of their growth, need for new talent, and increase in goals. Such values help improve the attractiveness of an industry to students, career changers or other industries looking to collaborate.

The bar chart depicts the job postings by industry, with a majority of postings within a select few industries. An Unclassified Industry has the highest amount of postings, amassing over 9,000. This lead is followed by other industries such as Custom Computer Programming Services, Administrative Management and General Management Consulting Services, Employment Placement Agencies, and Computer Systems Design Services in descending value and number of job postings between 5,000 and 4,000.

The remaining industries amount to a much smaller number of postings, which indicates their low representation. This lower hiring demand could be a result of disinterest in field from college graduates and skilled professionals or the lack of proper outreach about such industries to the general public. Either way, it is evident that the industries that deal with computer-based technology have higher volumes of job postings to meet the demand of companies and other businesses within their sector.

## Salary Distribution by Industry
```{python echo=false}

import plotly.express as px


top_industries = df["NAICS_2022_6_NAME"].value_counts().head(20).index

df_top = df[df["NAICS_2022_6_NAME"].isin(top_industries)]

fig = px.box(df_top, x="NAICS_2022_6_NAME",      y="SALARY",
            title="Salary Distribution by Industry",
            labels={"NAICS_2022_6_NAME": "Industry", "SALARY": "Salary"},
            width=900,
            height=600)

fig.update_xaxes(tickangle=45)

fig.write_html("figures/Salary_Distribution_by_Industry.html")




```


```{=html}
<iframe src="figures/Salary_Distribution_by_Industry.html" width="900" height="600" frameborder="0"></iframe>
```


As salary is a strong determining factors in people's choice of career and deciding between industries, it is important to evaluate how 20 industries published by NAICS compensate their talent across the board. Some industries like Software Publishers, Administrative Management and General Management Consultant Services, and Web Search Portals and All Other Information Services display wide salary spreads, indicated by tall boxes in the plot. These industires also have large high-salary outliers, with salaries reaching almost $500k.

The median and interquartile ranges also differ between industries. For example, the Temporary Help Services and Direct Health and Medical Insurance Carriers industries have the tighter cluster of salaries, suggesting more consistent pay ranges in various subsectors and across titles and other levels of seniority. Unlike the other widespread industries, where salary expectations might differ drastically from company to company or region to region. 

Overall, this distribution highlights how industry choice can also affect earning potential in the long-run and cap salaries despite years of experience, skillset, or educational level.


## Remote vs. On-Site Jobs
```{python echo=false}
import plotly.express as px
fig = px.pie(df, names="REMOTE_TYPE_NAME", title="Remote vs. On-Site Jobs")



fig.write_html("figures/remote_vs_On_site.html")



```


```{=html}
<iframe src="figures/remote_vs_On_site.html" width="900" height="600" frameborder="0"></iframe>
```

After 2020, there has been a large influx of the necessity for work-life balance and that priority was heavily influenced by remote work that maintained industries during the COVID-19 lockdown mandates. However, as society moves past the time of quarantine, it is becoming a prevalent question on if these multitude of remote jobs that offer flexibilty would be carried along into the future.

The piechart shows how the lack of proper documentaion can affect analysis as 78.3% of jobs are not classified as remote, hybrid remote, or not remote. Although, this took up the larger portion of the diagram, 17% of those jobs are Remote, with another 3.11% being Hybrid remote (some days in-office and others virtually), which account for a fifith of all job postings. This demonstrates that flexible work arrangements are an important factor to both the industry, in terms of their expecations for performance, as well as applicants and their need to for a healthy balance between work and personal life. 

Additionally, less than 2% of jobs are not Remote or are completely on-site which further corroborates the idea that employers prefer and adveritse flexibilty over strict in-person requirements. 




